### ISSUE TITLE
Doesn't compile fine for any configuration

### ISSUE THREAD

**Issue by hlide** [jmcnamara/MSVCLibXlsxWriter#2]
I selected "Release/x86" configuration then click "Build", I got compiling errors.

It is clear that those visual studio project files were never tested against all configurations (at least it wasn't for win32).

Github is plagued with such half-working projects and so less compelling to embrace.

**Comment by jmcnamara** [comment]
> Github is plagued with such half-working projects 

GitHub is also plagued with incomplete bug reports. 

* What steps did you follow? Please copy and paste. 
* Does compilation work for the default configuration?
* What version of MSVC are you using?
* If you are familiar with CMake can you try that with the master branch of libxlsxwriter?

Regards,

John.

**Comment by hlide** [comment]
It only worked with "Debug/x64" configuration. I had to modify project stuff like "include path" to make it work with the other configurations.

For your record, I also tried with cmake on the other repository "libxlsxwriter" but failed because it was unable to retrieve stuff like zlib. I followed what was written on  "https://libxlsxwriter.github.io/getting_started.html#gsg_cmake_generators". However, I did try cmake only on release 0.7.0.

**Comment by hlide** [comment]
Let me recheck something...

**Comment by hlide** [comment]
So, I retried the following case:
- clone with GIT this repository
- open the solution to create the wanted DLL by double-clicking on it.
- wait for vs2015 opening the solution (so the solution was created with vs2015).
- select a different configuration: Release instead of Debug, win32 instead of x64.
- build.

I got errors such: `1>  app.c
1>..\..\libxlsxwriter\src\app.c(10): fatal error C1083: Cannot open include file: 'xlsxwriter/xmlwriter.h': No such file or directory`.
If you look at project property, you can see the other configurations have a faulty include path compared with the default configuration. So this is a half-working project file.

**Comment by jmcnamara** [comment]
> I retried the following case: clone with GIT this repository

What command did you use?

**Comment by hlide** [comment]
`git.exe  clone -v --recurse-submodules --progress "https://github.com/jmcnamara/MSVCLibXlsxWriter.git" "C:/GIT/MSVCLibXlsxWriter3"`

**Comment by hlide** [comment]
here the output of the command:
```
Cloning into 'C:/GIT/MSVCLibXlsxWriter3'...                                                  
POST git-upload-pack (175 bytes)                                                             
remote: Counting objects: 124, done.                                                         
Rremote: Total 124 (delta 0), reused 0 (delta 0), pack-reused 124                            
Receiving objects:  49% (61/124), 956.01 KiB | 1.82 MiB/s                                    
Receiving objects: 100% (124/124), 1.45 MiB | 1.82 MiB/s, done.                              
Resolving deltas: 100% (61/61), done.                                                        
Submodule 'libxlsxwriter' (https://github.com/jmcnamara/libxlsxwriter.git) registered for path 'libxlsxwriter'                                                                            
Cloning into 'C:/GIT/MSVCLibXlsxWriter3/libxlsxwriter'...                                    
remote: Counting objects: 7591, done.                                                        
remote: Compressing objects: 100% (11/11), done.                                             
remote: Total 7591 (delta 2), reused 10 (delta 2), pack-reused 7578                          
Receiving objects: 100% (7591/7591), 13.70 MiB | 6.15 MiB/s, done.                           
Resolving deltas: 100% (5622/5622), done.                                                    
Submodule path 'libxlsxwriter': checked out '56064038a40a6a5393b71e03e48ca369b964ae4f'       
Done
```

**Comment by jmcnamara** [comment]
Fixed on master.
